config/routes.rb
Rails.application.routes.draw do

root   'static_pages#home'
get    '/signup', to: 'users#new'
get    '/login',  to: 'sessions#new'
post   '/login',  to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'

resources :users,  only: [:index, :new, :create, :show]
resources :events
resources :attendings, only: [:new, :create, :destroy]
resources :comments, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attending.rb
class Attending < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: 'User'
  validates :attendee_id, uniqueness: { scope: :event_id}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  scope :future, -> { where("date > ?", Date.today) }
  scope :past,   -> { where("date < ?", Date.today) }

  belongs_to :creator, class_name: 'User'
  has_many :attendings
  has_many :attendees, through: :attendings
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  has_many :attendings, foreign_key: :attendee_id
  has_many :events, through: :attendings
  has_many :comments
  validates :name,  presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  #Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/attendings_controller.rb
class AttendingsController < ApplicationController

  def new
    @event = Event.find(params[:event_id])
  end

  def create
    event_id    = params[:attending][:event_id]
    attendee_id = current_user.id
    @attendee = Attending.new(event_id: event_id, attendee_id: attendee_id)
    @attendee.save
    if @attendee.save
      flash[:success] = "Reservation confirmed! Looking forward to seeing you!"
      redirect_to event_path(event_id)
    end
  end

  def attendee_params
    params.require(:attending).permit(attending_attributes: [:attendee_id, :event_id])
  end

  def destroy
    id = params[:id]
    event_id = params[:attending][:event_id]
    @attendee = Attending.where(id: id).first
    @attendee.destroy
    flash[:success] = "RSVP Canceled. Sorry you can't make it!"
    redirect_to event_path(event_id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
  end

  def create
    event_id = params[:comment][:event_id]
    user_id  = current_user.id
    @event = Event.where(id: event_id).first
    @comment = @event.comments.build(comment_params)
    if @comment.save
      flash[:success] = "Comment created!"
      redirect_to @event
    else
      flash[:danger] = "error! please try again"
      render 'static_pages/home'
    end
  end

  def show
    @comments = @event.comments
  end

  def destroy
    comment_id = params[:id]
    @comment = Comment.find_by(id: comment_id)
    @comment.destroy
    flash[:success] = "Comment deleted"
    redirect_to root_url
  end

  private

  def comment_params
      params.require(:comment).permit(:content, :event_id, :user_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :index, :show, :new]
  def index
    @future_events = Event.future
    @past_events   = Event.past
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    @event.save
    redirect_to @event
  end

  def show
    @event = Event.find(params[:id])

    @comment = @event.comments.build(user_id: current_user.id)
    @attendees = @event.attendees
    if @attendees.include?(current_user)
      @attendee = Attending.find_by(event_id: @event.id, attendee_id: current_user.id)
    else
      @attendee = @event.attendings.build(attendee_id: current_user.id)
    end
    @comment_feed = @event.comments.where("content != ?", '').all
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:success] = "Event updated!"
      log_in @event
      redirect_to @event
    else
      flash[:warning] = "Error updating event. Please try again."
      render 'edit'
    end
  end

  def destroy
    Event.find(params[:id]).destroy
  end

  private
    def event_params
      params.require(:event).permit(:name, :creator, :location, :date, :description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user != nil
      log_in user
      redirect_to session[:forwarding_url] || root_url
    else
      message = "Account does not exist. Click 'Sign Up' to create an account"
      flash[:warning] = message
      redirect_to login_url
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      redirect_to '/events'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account created! You are now logged in!"
      log_in @user
      redirect_to root_url
    else
      flash[:warning] = "That name is already taken. Please try again."
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @created_events = @user.created_events
    @past_events = @user.events.past
    @future_events = @user.events.future
  end

  private
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendings_helper.rb
module AttendingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/description_helper.rb
module DescriptionHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    cookies.delete(:user_id)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendings/_new.html.erb
  <div>
    <%= form_for(@attendee) do |f| %>
      <%= f.hidden_field :event_id %>
      <%= f.submit "i'll be there!", class: "btn btn-primary btn-big" %>
    <% end %>
  </div>

app/views/comments/_comment.html.erb
<%- @comment_feed.each do |c| %>
  <li id="comment">
    <span class="user"><%= link_to c.user.name, c.user %></span>
    <span class="content">
      <%= c.content %>
    </span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(c.created_at) %> ago.
      <% if current_user?(c.user) %>
        <%= link_to "delete", c, method: :delete,
                                 data: { confirm: "You sure?" },
                                 class: "delete" %>
      <% end %>
    </span>
  </li>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <br>
  <%= f.hidden_field :event_id %>
  <%= f.hidden_field :user_id %>
  <%= f.text_area :content,
                  placeholder: "Can't make it? Any questions? Bringing something? Mention it here!",
                  class: 'form-control' %>

  <%= f.submit "Post comment", class: "btn btn-primary" %>
<% end %>

app/views/events/_event.html.erb
<li>
  <%= link_to event.name, event %>
</li>

app/views/events/_form.html.erb
<% button_text = "#{action} event" %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>
      <br>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label :date %>
      <%= f.date_field :date, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.submit button_text, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/_future.html.erb
<section class="user_info">
  <h1>future events</h1>
  <%= @future_events.each do |e| %>
    <h1>
      <%= e.name %>
    </h1>
    <ul class="event-card">
      <li>Location: <%= e.location %></li>
      <li>Creator: <%= e.creator.name %></li>
      <li>Date: <%= e.date %></li>
    </ul>
    <ul>
      <h1>Attendees</h1>
      <% e.attendees.each do |a| %>
        <li><%= link_to "#{a.name}", user_path %></li>
      <% end %>
    </ul>
  <% end %>
</section>

app/views/events/_past.html.erb
<section class="user_info">
  <h1>past events</h1>
  <%= @past_events.each do |e| %>
    <h1>
      <%= e.name %>
    </h1>
    <ul class="event-card">
      <li>Location: <%= e.location %></li>
      <li>Creator: <%= e.creator.name %></li>
      <li>Date: <%= e.date %></li>
    </ul>
    <ul>
      <h1>Attendees</h1>
      <% e.attendees.each do |a| %>
        <li><%= link_to "#{a.name}", user_path %></li>
      <% end %>
    </ul>
  <% end %>
</section>

app/views/events/edit.html.erb
<h1>Update your event</h1>

<%= render 'events/form', action: 'Update'%>

app/views/events/index.html.erb
<ul class="users">
  <h1>future events</h1>
  <%= render @future_events %>
  <h1>past events</h1>
  <%= render @past_events %>
</ul>

app/views/events/new.html.erb
<h1>Create an event</h1>

<%= render 'events/form', action: 'New'%>

app/views/events/show.html.erb
<div class="row">
  <aside class="col-md-12">
    <section class="user_info">
      <h1 class="big-title">
        <%= @event.name %>
      </h1>
      <ul class="event-card">
        <% if current_user == @event.creator %>
            <%= link_to "Edit", edit_event_path(@event), class: 'btn btn-primary event-edit' %>
        <% end %>
        <li class="event-items">Location: <%= @event.location %></li>
        <li>Creator: <%= @event.creator.name %></li>
        <li>Date: <%= @event.date %></li>
        <li>Description: <%= @event.description %></li>
      </ul>

      <br>
      <div class="col-md-4 attendee-list">
        <div>
          <% if current_user.attendings.where(event_id: @event.id).exists? %>
            <%= form_for @attendee, method: :delete do |f| %>
              <%= f.hidden_field :event_id %>
              <%= f.submit "cancel rsvp", class: "btn btn-primary btn-red btn-big" %>
            <% end %>
          <% else %>
            <%= render 'attendings/new' %>
          <% end %>
        </div>
        <ul>
          <h1>Attendees</h1>
          <% @event.attendees.each do |a| %>
            <li><%= link_to "#{a.name}", "/users/#{a.id}", class: "attendee" %></li>
          <% end %>
        </ul>
      </div>
      <div class="col-md-1">
      </div>
      <div class="col-md-7 comment-feed">
        <h1>Comments</h1>
        <%= render 'comments/form' %>
        <% if @comment_feed.present? %>
            <%= render 'comments/comment' %>
        <% end %>
      </div>

    </section>
  </aside>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <a class="icons" href="https://github.com/thewmking">
    <div class="fa fa-crown"></div>
    <div class="fa fa-calendar"></div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "king events", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "home",   root_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              events <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "new event", new_event_path %></li>
              <li><%= link_to "view all",  events_path %></li>
            </ul>
          </li>
          <li><%= link_to "users", users_path %></li>
          <li><%= link_to "log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>King Events</title>
    <%= render 'layouts/rails_default' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <% if Rails.env.development? %>
        <%= debug(params) %>
        <%= console %>
      <% end %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="col-md-12">
  <h1>welcome to <strong>king</strong> events!</h1>
  <div class="col-md-6">
    <%= link_to "log in", login_path, class: "btn btn-primary btn-big home" %>
  </div>
  <div class="col-md-6">
    <%= link_to "sign up", signup_path, class: "btn btn-primary btn-big home" %>
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  
</li>

app/views/users/index.html.erb
<h1>All users</h1>


<ul class="users">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <br>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
        <br>
        created events
      </h1>
      <div>
        <% @created_events.each do |e| %>
          <ul class="event-card">
            <li class="event-link"><%= link_to "#{e.name}", "/events/#{e.id}" %></li>
            <li>Location: <%= e.location %></li>
            <li>Date: <%= e.date %></li>
          </ul>
        <% end %>
      </div>
      <div>
        <h1>events <%= @user.name %> is attending:</h1>
        <ul>
          <h1>past events</h1>
          <% @past_events.each do |e| %>
            <li><%= link_to "#{e.name}", "/events/#{e.id}" %></li>
          <% end %>
        </ul>
        <ul>
          <h1>future events</h1>
          <% @future_events.each do |e| %>
            <li><%= link_to "#{e.name}", "/events/#{e.id}" %></li>
          <% end %>
        </ul>
      </div>

    </section>
</div>